server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: kopring-jpa-demo

  profiles:
    active: local

  config:
    import:
      - classpath:/configs/application-proxy.yml
      - classpath:/configs/application-local.yml
