server:
  port: 18080

spring:
  application:
      name: cloud-gateway
  cloud:
    gateway:

      # Global Filter
      default-filters:
        - name: GlobalFilter
        - name: LoggingFilter

      # Routing
      routes:
        - id: boot-basic
          uri: http://localhost:8080
          predicates:
            - Path=/api/basic
            - After=2020-01-01T00:00:00+08:00[Asia/Seoul]
#          filters:
#            - CustomFilter # Custom Filter(order=1)