server:
  port: 18080

spring:
  application:
      name: cloud-gateway
  cloud:
    gateway:

      # Global Filter
      default-filters:
        - name: GlobalFilter
        - name: LoggingFilter

      # Routing
      routes:
        - id: boot-basic
          uri: http://localhost:8080
          predicates:
            - Path=/api/basic
            - After=2020-01-01T00:00:00+08:00[Asia/Seoul]
#          filters:
#            - CustomFilter # Custom Filter(order=1)



# Actuator - ???? Sample
management:
  # 1. use Other port for Actuator
  server:
    port: 8070
  # 2. Endpoint All disable
  enabled-by-default: false
  # 3. Actuator Endpoints Enable
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    # 4. Exclude All JMX End points And Expose specific endpoints
#    jmx:
#      exposure:
#        exclude: '*'
    web:
      exposure:
        include: prometheus, info, health
      # 5. Actuator Base Path -> /actuator to /monitoring
      base-path: /monitoring