server:
  port: 8080
  shutdown: graceful


spring:
  application:
    name: hexagonal-kotlin

  profiles:
    active: proxy

  config:
    import:
      - classpath:/configs/application-proxy.yml
      - classpath:/configs/application-local.yml
